CREATE TABLE IF NOT EXISTS check_log (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tem1_raw TEXT NOT NULL,
    tem2_raw TEXT NOT NULL,
    tem1_product VARCHAR(120) DEFAULT NULL,
    tem1_qty INT DEFAULT NULL,
    tem2_product VARCHAR(120) DEFAULT NULL,
    tem2_qty INT DEFAULT NULL,
    is_product_match TINYINT(1) NOT NULL DEFAULT 0,
    is_qty_match TINYINT(1) NOT NULL DEFAULT 0,
    result_code VARCHAR(50) DEFAULT NULL,
    result_message VARCHAR(255) DEFAULT NULL,
    type VARCHAR(50) NOT NULL DEFAULT 'check box',
    scanned_by VARCHAR(50) NOT NULL,
    scanned_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_check_log_scanned_at (scanned_at),
    KEY idx_check_log_scanned_by (scanned_by),
    KEY idx_check_log_type (type),
    KEY idx_check_log_result_code (result_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
